version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
  # post_build:
    # commands:
      # - npm test
# artifacts:
  # base-directory: 'api/dist'
  # files:
  #   - 'api/dist/index.zip'
  #   - 'api/dist/appspec.yml'
  # discard-paths: true
