version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm i -g yarn
  build:
    commands:
      - yarn install
      - tsc --noemit
      - npm run build
artifacts:
  files:
    - 'build/**/*'
cache:
  paths:
    - 'yarn.lock'
