version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
      - npm run build:zip
  # post_build:
  #   commands:
  #     - npm test
artifacts:
  type: YAML
  secondary-artifacts:
    D001:
      files:
        - D001.zip
        - appspec.yml
      base-directory: dist/D0_D001
    D002:
      files:
        - D002.zip
        - appspec.yml
      base-directory: dist/D0_D002

