version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
      - npm i -g yarn
  build:
    commands:
      - yarn install
      - npm run build:prod
      - cp publish/* build/
      - cd build
      - yarn install
      - npm run start
artifacts:
  files:
    - 'build/**/*'
