version: 0.2

phases:
  pre_build:
    commands:
      - echo hello
  build:
    commands:
      - npm install  
  post_build:
    commands:
      - npm test
# artifacts:
  # base-directory: 'api/dist'
  # files:
  #   - 'api/dist/index.zip'
  #   - 'api/dist/appspec.yml'
  # discard-paths: true
