version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
      - npm run build:zip
  # post_build:
  #   commands:
  #     - npm test
artifacts:
  secondary-artifacts:
    D001:
      files:
        - D001.zip
      base-directory: dist
    D002:
      files:
        - D002.zip
      base-directory: dist

