version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
      - npm run build:zip
  # post_build:
  #   commands:
  #     - npm test
artifacts:
  files:
    - buildspec_publish.yml
    - publish/main.ts
    - publish/package.json
    - publish/tsconfig.json
    - dist/D0_D001/D001.zip
    - dist/D0_D002/D002.zip
  discard-paths: yes
  # type: YAML
  # secondary-artifacts:
  #   D001:
  #     files:
  #       - D001.zip
  #     base-directory: dist/D0_D001
  #   D002:
  #     files:
  #       - D002.zip
  #       - appspec.yml
  #     base-directory: dist/D0_D002

