version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm i -g yarn
  build:
    commands:
      - yarn install
      - yarn valid
      - yarn build
      - yarn coverage
      - docker build -t backend .
artifacts:
  files:
    - 'build/**/*'
cache:
  paths:
    - 'yarn.lock'
