# https://cloud.google.com/cloud-build/docs/build-config?hl=ja
steps:
  # Library Install
  - name: gcr.io/cloud-builders/yarn
    args:
      - install
      - --ignore-engines
  # Audit
  # - name: node:10.15.3-alpine
  #   entrypoint: yarn
  #   args:
  #     - audit
  #     - --level
  #     - high
  #     - critical
  # Source Build
  - name: gcr.io/cloud-builders/yarn
    entrypoint: yarn
    args:
      - build
  # Docker Build
  - name: gcr.io/cloud-builders/docker
    dir: build/cloudrun
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/backend:latest
      - .
  # Docker Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/backend:latest
  # Test
  # - name: node:10.15.3-alpine
  #   entrypoint: yarn
  #   args:
  #     - test
  #   env:
  #     - "ENVIRONMENT=$_ENVIRONMENT"
  # Terraform Initialize
  - name: hashicorp/terraform:0.12.24
    dir: terraform
    entrypoint: terraform
    args:
      - init
  # Switch Workspace
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: terraform
    args:
      - workspace
      - select
      - $_ENVIRONMENT
      - -no-color
  # Plan
  - name: hashicorp/terraform:0.12.24
    dir: terraform
    entrypoint: terraform
    args:
      - plan
      - -out=tfplan
      - -no-color
  # Apply
  - name: hashicorp/terraform:0.12.24
    dir: terraform
    entrypoint: terraform
    args:
      - apply
      - tfplan
      - -no-color
