version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      docker: 18
  pre_build:
    commands:
      - npm i -g yarn
  build:
    commands:
      - yarn install
      - yarn start
cache:
  paths:
    - 'yarn.lock'
