version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb,s3
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - './localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
