version: '3'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb,s3,ssm,secretsmanager
      - DATA_DIR=/usr/local/data
      - DEFAULT_REGION=ap-northeast-1
    # volumes:
    # - './localstack:/tmp/localstack'
    # - '/var/run/docker.sock:/var/run/docker.sock'
