version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget -q https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip
      - unzip terraform_0.12.17_linux_amd64.zip
      - mv terraform /bin
  build:
    commands:
      - cp -r $CODEBUILD_SRC_DIR_build_artf/build build
      - cd infra
      - terraform init -no-color
      - terraform workspace select $ENVIRONMENT -no-color
      - terraform plan -out tfplan -no-color
      - terraform apply tfplan -no-color
      - cd $CODEBUILD_SRC_DIR
      - node publish/index.js
