version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm i -g yarn
  build:
    commands:
      - cp publish/* $CODEBUILD_SRC_DIR_build_artf/
      - cd $CODEBUILD_SRC_DIR_build_artf
      - ls
      - yarn install
      - npm run start
artifacts:
  files:
    - 'build/**/*'
