name: Backend

on:
  push:
    branches:
      - master
    paths-ignore:
      - docker/**
      - .github/workflows/dockerbuild.yml

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  # Docker Build
  Build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@master

      # install nodejs
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      # Library install
      - name: install and build
        run: |
          yarn install
          yarn build

  # Docker image deploy
  Deploy:
    needs:
      - Build

    runs-on: ubuntu-latest

    steps:
      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Push to ECR
      - name: ECR Push
        run: |
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pocket-cards/backend

  Pulumi:
    needs:
      - Build

    runs-on: ubuntu-latest

    steps:
      # select stack
      - uses: docker://pulumi/actions
        with:
          args: stack select dev-backend
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_ROOT: pulumi

      # stack update
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: pulumi
